// Code generated by entc, DO NOT EDIT.

package txs

import (
	"github.com/pepeunlimited/accounts/internal/pkg/ent/schema"
)

const (
	// Label holds the string label denoting the txs type in the database.
	Label = "txs"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTxType holds the string denoting the tx_type vertex property in the database.
	FieldTxType = "tx_type"
	// FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt = "created_at"
	// FieldAmount holds the string denoting the amount vertex property in the database.
	FieldAmount = "amount"
	// FieldReferenceNumber holds the string denoting the reference_number vertex property in the database.
	FieldReferenceNumber = "reference_number"

	// Table holds the table name of the txs in the database.
	Table = "txs"
	// AccountsTable is the table the holds the accounts relation/edge.
	AccountsTable = "txs"
	// AccountsInverseTable is the table name for the Accounts entity.
	// It exists in this package in order to avoid circular dependency with the "accounts" package.
	AccountsInverseTable = "accounts"
	// AccountsColumn is the table column denoting the accounts relation/edge.
	AccountsColumn = "accounts_id"
)

// Columns holds all SQL columns for txs fields.
var Columns = []string{
	FieldID,
	FieldTxType,
	FieldCreatedAt,
	FieldAmount,
	FieldReferenceNumber,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Txs type.
var ForeignKeys = []string{
	"accounts_id",
}

var (
	fields = schema.Txs{}.Fields()

	// descTxType is the schema descriptor for tx_type field.
	descTxType = fields[0].Descriptor()
	// TxTypeValidator is a validator for the "tx_type" field. It is called by the builders before save.
	TxTypeValidator = func() func(string) error {
		validators := descTxType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(tx_type string) error {
			for _, fn := range fns {
				if err := fn(tx_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()

	// descReferenceNumber is the schema descriptor for reference_number field.
	descReferenceNumber = fields[3].Descriptor()
	// ReferenceNumberValidator is a validator for the "reference_number" field. It is called by the builders before save.
	ReferenceNumberValidator = descReferenceNumber.Validators[0].(func(string) error)
)
