// Code generated by entc, DO NOT EDIT.

package txs

import (
	"github.com/pepeunlimited/accounts/internal/pkg/ent/predicate"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Txs {
	return predicate.Txs(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldID), id))
		},
	)
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	},
	)
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	},
	)
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	},
	)
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	},
	)
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	},
	)
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	},
	)
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	},
	)
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	},
	)
}

// TxType applies equality check predicate on the "tx_type" field. It's identical to TxTypeEQ.
func TxType(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTxType), v))
	},
	)
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	},
	)
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAmount), v))
	},
	)
}

// ReferenceNumber applies equality check predicate on the "reference_number" field. It's identical to ReferenceNumberEQ.
func ReferenceNumber(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldReferenceNumber), v))
	},
	)
}

// TxTypeEQ applies the EQ predicate on the "tx_type" field.
func TxTypeEQ(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTxType), v))
	},
	)
}

// TxTypeNEQ applies the NEQ predicate on the "tx_type" field.
func TxTypeNEQ(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTxType), v))
	},
	)
}

// TxTypeIn applies the In predicate on the "tx_type" field.
func TxTypeIn(vs ...string) predicate.Txs {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Txs(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTxType), v...))
	},
	)
}

// TxTypeNotIn applies the NotIn predicate on the "tx_type" field.
func TxTypeNotIn(vs ...string) predicate.Txs {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Txs(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTxType), v...))
	},
	)
}

// TxTypeGT applies the GT predicate on the "tx_type" field.
func TxTypeGT(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTxType), v))
	},
	)
}

// TxTypeGTE applies the GTE predicate on the "tx_type" field.
func TxTypeGTE(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTxType), v))
	},
	)
}

// TxTypeLT applies the LT predicate on the "tx_type" field.
func TxTypeLT(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTxType), v))
	},
	)
}

// TxTypeLTE applies the LTE predicate on the "tx_type" field.
func TxTypeLTE(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTxType), v))
	},
	)
}

// TxTypeContains applies the Contains predicate on the "tx_type" field.
func TxTypeContains(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTxType), v))
	},
	)
}

// TxTypeHasPrefix applies the HasPrefix predicate on the "tx_type" field.
func TxTypeHasPrefix(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTxType), v))
	},
	)
}

// TxTypeHasSuffix applies the HasSuffix predicate on the "tx_type" field.
func TxTypeHasSuffix(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTxType), v))
	},
	)
}

// TxTypeEqualFold applies the EqualFold predicate on the "tx_type" field.
func TxTypeEqualFold(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTxType), v))
	},
	)
}

// TxTypeContainsFold applies the ContainsFold predicate on the "tx_type" field.
func TxTypeContainsFold(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTxType), v))
	},
	)
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	},
	)
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	},
	)
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Txs {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Txs(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	},
	)
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Txs {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Txs(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	},
	)
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	},
	)
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	},
	)
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	},
	)
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	},
	)
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAmount), v))
	},
	)
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAmount), v))
	},
	)
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.Txs {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Txs(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldAmount), v...))
	},
	)
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.Txs {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Txs(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldAmount), v...))
	},
	)
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAmount), v))
	},
	)
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAmount), v))
	},
	)
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAmount), v))
	},
	)
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAmount), v))
	},
	)
}

// ReferenceNumberEQ applies the EQ predicate on the "reference_number" field.
func ReferenceNumberEQ(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldReferenceNumber), v))
	},
	)
}

// ReferenceNumberNEQ applies the NEQ predicate on the "reference_number" field.
func ReferenceNumberNEQ(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldReferenceNumber), v))
	},
	)
}

// ReferenceNumberIn applies the In predicate on the "reference_number" field.
func ReferenceNumberIn(vs ...string) predicate.Txs {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Txs(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldReferenceNumber), v...))
	},
	)
}

// ReferenceNumberNotIn applies the NotIn predicate on the "reference_number" field.
func ReferenceNumberNotIn(vs ...string) predicate.Txs {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Txs(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldReferenceNumber), v...))
	},
	)
}

// ReferenceNumberGT applies the GT predicate on the "reference_number" field.
func ReferenceNumberGT(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldReferenceNumber), v))
	},
	)
}

// ReferenceNumberGTE applies the GTE predicate on the "reference_number" field.
func ReferenceNumberGTE(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldReferenceNumber), v))
	},
	)
}

// ReferenceNumberLT applies the LT predicate on the "reference_number" field.
func ReferenceNumberLT(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldReferenceNumber), v))
	},
	)
}

// ReferenceNumberLTE applies the LTE predicate on the "reference_number" field.
func ReferenceNumberLTE(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldReferenceNumber), v))
	},
	)
}

// ReferenceNumberContains applies the Contains predicate on the "reference_number" field.
func ReferenceNumberContains(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldReferenceNumber), v))
	},
	)
}

// ReferenceNumberHasPrefix applies the HasPrefix predicate on the "reference_number" field.
func ReferenceNumberHasPrefix(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldReferenceNumber), v))
	},
	)
}

// ReferenceNumberHasSuffix applies the HasSuffix predicate on the "reference_number" field.
func ReferenceNumberHasSuffix(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldReferenceNumber), v))
	},
	)
}

// ReferenceNumberIsNil applies the IsNil predicate on the "reference_number" field.
func ReferenceNumberIsNil() predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldReferenceNumber)))
	},
	)
}

// ReferenceNumberNotNil applies the NotNil predicate on the "reference_number" field.
func ReferenceNumberNotNil() predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldReferenceNumber)))
	},
	)
}

// ReferenceNumberEqualFold applies the EqualFold predicate on the "reference_number" field.
func ReferenceNumberEqualFold(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldReferenceNumber), v))
	},
	)
}

// ReferenceNumberContainsFold applies the ContainsFold predicate on the "reference_number" field.
func ReferenceNumberContainsFold(v string) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldReferenceNumber), v))
	},
	)
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AccountsTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	},
	)
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Accounts) predicate.Txs {
	return predicate.Txs(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AccountsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	},
	)
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Txs) predicate.Txs {
	return predicate.Txs(
		func(s *sql.Selector) {
			s1 := s.Clone().SetP(nil)
			for _, p := range predicates {
				p(s1)
			}
			s.Where(s1.P())
		},
	)
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Txs) predicate.Txs {
	return predicate.Txs(
		func(s *sql.Selector) {
			s1 := s.Clone().SetP(nil)
			for i, p := range predicates {
				if i > 0 {
					s1.Or()
				}
				p(s1)
			}
			s.Where(s1.P())
		},
	)
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Txs) predicate.Txs {
	return predicate.Txs(
		func(s *sql.Selector) {
			p(s.Not())
		},
	)
}
