// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "balance", Type: field.TypeInt64},
		{Name: "version", Type: field.TypeUint8},
		{Name: "type", Type: field.TypeString, Size: 4},
		{Name: "is_withdrawable", Type: field.TypeBool},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:        "accounts",
		Columns:     AccountsColumns,
		PrimaryKey:  []*schema.Column{AccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// TxsColumns holds the columns for the "txs" table.
	TxsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tx_type", Type: field.TypeString, Size: 10},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "reference_number", Type: field.TypeString, Nullable: true, Size: 36},
		{Name: "accounts_id", Type: field.TypeInt, Nullable: true},
	}
	// TxsTable holds the schema information for the "txs" table.
	TxsTable = &schema.Table{
		Name:       "txs",
		Columns:    TxsColumns,
		PrimaryKey: []*schema.Column{TxsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "txs_accounts_txs",
				Columns: []*schema.Column{TxsColumns[5]},

				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		TxsTable,
	}
)

func init() {
	TxsTable.ForeignKeys[0].RefTable = AccountsTable
}
