// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package rpcaccount

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateDepositParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDepositParams) Reset()         { *m = CreateDepositParams{} }
func (m *CreateDepositParams) String() string { return proto.CompactTextString(m) }
func (*CreateDepositParams) ProtoMessage()    {}
func (*CreateDepositParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *CreateDepositParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDepositParams.Unmarshal(m, b)
}
func (m *CreateDepositParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDepositParams.Marshal(b, m, deterministic)
}
func (m *CreateDepositParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDepositParams.Merge(m, src)
}
func (m *CreateDepositParams) XXX_Size() int {
	return xxx_messageInfo_CreateDepositParams.Size(m)
}
func (m *CreateDepositParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDepositParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDepositParams proto.InternalMessageInfo

type CreateDepositResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDepositResponse) Reset()         { *m = CreateDepositResponse{} }
func (m *CreateDepositResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDepositResponse) ProtoMessage()    {}
func (*CreateDepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *CreateDepositResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDepositResponse.Unmarshal(m, b)
}
func (m *CreateDepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDepositResponse.Marshal(b, m, deterministic)
}
func (m *CreateDepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDepositResponse.Merge(m, src)
}
func (m *CreateDepositResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDepositResponse.Size(m)
}
func (m *CreateDepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDepositResponse proto.InternalMessageInfo

type CreateWithdrawParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWithdrawParams) Reset()         { *m = CreateWithdrawParams{} }
func (m *CreateWithdrawParams) String() string { return proto.CompactTextString(m) }
func (*CreateWithdrawParams) ProtoMessage()    {}
func (*CreateWithdrawParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *CreateWithdrawParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWithdrawParams.Unmarshal(m, b)
}
func (m *CreateWithdrawParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWithdrawParams.Marshal(b, m, deterministic)
}
func (m *CreateWithdrawParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWithdrawParams.Merge(m, src)
}
func (m *CreateWithdrawParams) XXX_Size() int {
	return xxx_messageInfo_CreateWithdrawParams.Size(m)
}
func (m *CreateWithdrawParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWithdrawParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWithdrawParams proto.InternalMessageInfo

type CreateWithdrawResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWithdrawResponse) Reset()         { *m = CreateWithdrawResponse{} }
func (m *CreateWithdrawResponse) String() string { return proto.CompactTextString(m) }
func (*CreateWithdrawResponse) ProtoMessage()    {}
func (*CreateWithdrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *CreateWithdrawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWithdrawResponse.Unmarshal(m, b)
}
func (m *CreateWithdrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWithdrawResponse.Marshal(b, m, deterministic)
}
func (m *CreateWithdrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWithdrawResponse.Merge(m, src)
}
func (m *CreateWithdrawResponse) XXX_Size() int {
	return xxx_messageInfo_CreateWithdrawResponse.Size(m)
}
func (m *CreateWithdrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWithdrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWithdrawResponse proto.InternalMessageInfo

type CreateTransferParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTransferParams) Reset()         { *m = CreateTransferParams{} }
func (m *CreateTransferParams) String() string { return proto.CompactTextString(m) }
func (*CreateTransferParams) ProtoMessage()    {}
func (*CreateTransferParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *CreateTransferParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTransferParams.Unmarshal(m, b)
}
func (m *CreateTransferParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTransferParams.Marshal(b, m, deterministic)
}
func (m *CreateTransferParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTransferParams.Merge(m, src)
}
func (m *CreateTransferParams) XXX_Size() int {
	return xxx_messageInfo_CreateTransferParams.Size(m)
}
func (m *CreateTransferParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTransferParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTransferParams proto.InternalMessageInfo

type CreateTransferResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTransferResponse) Reset()         { *m = CreateTransferResponse{} }
func (m *CreateTransferResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTransferResponse) ProtoMessage()    {}
func (*CreateTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *CreateTransferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTransferResponse.Unmarshal(m, b)
}
func (m *CreateTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTransferResponse.Marshal(b, m, deterministic)
}
func (m *CreateTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTransferResponse.Merge(m, src)
}
func (m *CreateTransferResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTransferResponse.Size(m)
}
func (m *CreateTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTransferResponse proto.InternalMessageInfo

type CreateAccountParams struct {
	AccountType          string   `protobuf:"bytes,1,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountParams) Reset()         { *m = CreateAccountParams{} }
func (m *CreateAccountParams) String() string { return proto.CompactTextString(m) }
func (*CreateAccountParams) ProtoMessage()    {}
func (*CreateAccountParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *CreateAccountParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountParams.Unmarshal(m, b)
}
func (m *CreateAccountParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountParams.Marshal(b, m, deterministic)
}
func (m *CreateAccountParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountParams.Merge(m, src)
}
func (m *CreateAccountParams) XXX_Size() int {
	return xxx_messageInfo_CreateAccountParams.Size(m)
}
func (m *CreateAccountParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountParams proto.InternalMessageInfo

func (m *CreateAccountParams) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

type GetAccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAccountsResponse) Reset()         { *m = GetAccountsResponse{} }
func (m *GetAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountsResponse) ProtoMessage()    {}
func (*GetAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *GetAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsResponse.Unmarshal(m, b)
}
func (m *GetAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsResponse.Merge(m, src)
}
func (m *GetAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountsResponse.Size(m)
}
func (m *GetAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsResponse proto.InternalMessageInfo

func (m *GetAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type GetAccountParams struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountParams) Reset()         { *m = GetAccountParams{} }
func (m *GetAccountParams) String() string { return proto.CompactTextString(m) }
func (*GetAccountParams) ProtoMessage()    {}
func (*GetAccountParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{8}
}

func (m *GetAccountParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountParams.Unmarshal(m, b)
}
func (m *GetAccountParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountParams.Marshal(b, m, deterministic)
}
func (m *GetAccountParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountParams.Merge(m, src)
}
func (m *GetAccountParams) XXX_Size() int {
	return xxx_messageInfo_GetAccountParams.Size(m)
}
func (m *GetAccountParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountParams proto.InternalMessageInfo

func (m *GetAccountParams) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type Account struct {
	Balance              int64    `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id                   int64    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{9}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Account) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Account) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateDepositParams)(nil), "pepeunlimited.accounts.CreateDepositParams")
	proto.RegisterType((*CreateDepositResponse)(nil), "pepeunlimited.accounts.CreateDepositResponse")
	proto.RegisterType((*CreateWithdrawParams)(nil), "pepeunlimited.accounts.CreateWithdrawParams")
	proto.RegisterType((*CreateWithdrawResponse)(nil), "pepeunlimited.accounts.CreateWithdrawResponse")
	proto.RegisterType((*CreateTransferParams)(nil), "pepeunlimited.accounts.CreateTransferParams")
	proto.RegisterType((*CreateTransferResponse)(nil), "pepeunlimited.accounts.CreateTransferResponse")
	proto.RegisterType((*CreateAccountParams)(nil), "pepeunlimited.accounts.CreateAccountParams")
	proto.RegisterType((*GetAccountsResponse)(nil), "pepeunlimited.accounts.GetAccountsResponse")
	proto.RegisterType((*GetAccountParams)(nil), "pepeunlimited.accounts.GetAccountParams")
	proto.RegisterType((*Account)(nil), "pepeunlimited.accounts.Account")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0xaf, 0xd2, 0x40,
	0x10, 0x0d, 0x1f, 0xb9, 0x78, 0x87, 0x7b, 0x89, 0xd9, 0x2b, 0xa5, 0xa9, 0x51, 0xb1, 0x4f, 0x24,
	0xea, 0x12, 0xf1, 0xc5, 0xc4, 0x27, 0xbf, 0x62, 0x78, 0x33, 0x95, 0x84, 0xc4, 0xc4, 0xe8, 0xd2,
	0x0e, 0xb8, 0x11, 0xda, 0xcd, 0xee, 0x56, 0xc2, 0x4f, 0xf6, 0x5f, 0x18, 0xb6, 0xbb, 0x60, 0xf9,
	0xb0, 0xbc, 0xb5, 0x67, 0xe6, 0xcc, 0x9c, 0x99, 0x39, 0x0b, 0xb7, 0x2c, 0x8e, 0xb3, 0x3c, 0xd5,
	0x54, 0xc8, 0x4c, 0x67, 0xc4, 0x13, 0x28, 0x30, 0x4f, 0x97, 0x7c, 0xc5, 0x35, 0x26, 0xd4, 0x06,
	0x55, 0xf0, 0x70, 0x91, 0x65, 0x8b, 0x25, 0x0e, 0x4d, 0xd6, 0x2c, 0x9f, 0x0f, 0x71, 0x25, 0xf4,
	0xa6, 0x20, 0x05, 0x8f, 0x0f, 0x83, 0x6b, 0xc9, 0x84, 0x40, 0xa9, 0x8a, 0x78, 0xd8, 0x85, 0xbb,
	0xf7, 0x12, 0x99, 0xc6, 0x0f, 0x28, 0x32, 0xc5, 0xf5, 0x67, 0x26, 0xd9, 0x4a, 0x85, 0x3d, 0xe8,
	0x96, 0xe0, 0x08, 0x95, 0xc8, 0x52, 0x85, 0xa1, 0x07, 0x0f, 0x8a, 0xc0, 0x94, 0xeb, 0x9f, 0x89,
	0x64, 0x6b, 0x4b, 0xf0, 0xc1, 0x2b, 0xe3, 0xc7, 0x8c, 0x89, 0x64, 0xa9, 0x9a, 0xa3, 0x3c, 0x64,
	0x38, 0x7c, 0xc7, 0x78, 0xed, 0x34, 0xbd, 0x2d, 0x46, 0x2c, 0x08, 0xe4, 0x29, 0xdc, 0xd8, 0x99,
	0xbf, 0xeb, 0x8d, 0x40, 0xbf, 0xd6, 0xaf, 0x0d, 0xae, 0xa3, 0xb6, 0xc5, 0x26, 0x1b, 0x81, 0x61,
	0x04, 0x77, 0x9f, 0x50, 0x5b, 0x9a, 0x72, 0x05, 0xc9, 0x1b, 0xb8, 0xe7, 0xb6, 0xe5, 0xd7, 0xfa,
	0x8d, 0x41, 0x7b, 0xf4, 0x84, 0x9e, 0x5e, 0x26, 0xb5, 0xdc, 0x68, 0x47, 0x08, 0x5f, 0xc2, 0xfd,
	0x7d, 0x4d, 0x2b, 0xe5, 0x11, 0x80, 0x93, 0xc2, 0x13, 0x23, 0xa4, 0x11, 0x5d, 0x5b, 0x64, 0x9c,
	0x84, 0x3f, 0xa0, 0x65, 0xf3, 0x89, 0x0f, 0xad, 0x19, 0x5b, 0xb2, 0x34, 0x46, 0x9b, 0xe6, 0x7e,
	0x09, 0x81, 0xa6, 0x19, 0xa3, 0x6e, 0xc6, 0x30, 0xdf, 0xa4, 0x07, 0xad, 0x5c, 0xa1, 0xdc, 0x16,
	0x6d, 0x98, 0xec, 0xab, 0xed, 0xef, 0x38, 0x21, 0x1d, 0xa8, 0xf3, 0xc4, 0x6f, 0x1a, 0xac, 0xce,
	0x93, 0xd1, 0x9f, 0x26, 0x74, 0x6c, 0x8b, 0x2f, 0x28, 0x7f, 0xf3, 0x18, 0xc9, 0x2f, 0xb8, 0x2d,
	0x9d, 0x8c, 0x3c, 0x3b, 0x37, 0xe3, 0x89, 0x83, 0x07, 0x2f, 0x2e, 0x4a, 0xde, 0x6d, 0x34, 0x85,
	0x4e, 0xf9, 0xdc, 0xe4, 0xf9, 0xff, 0x0b, 0x94, 0xed, 0x12, 0xd0, 0xcb, 0xb2, 0x8f, 0xfb, 0x39,
	0xb3, 0x54, 0xf5, 0x2b, 0x9b, 0xad, 0xaa, 0xdf, 0xa1, 0x05, 0xc9, 0x37, 0xb7, 0x4c, 0x77, 0xc7,
	0x8a, 0x65, 0x96, 0xec, 0x11, 0x54, 0xb9, 0x8b, 0x44, 0xd0, 0xfe, 0xc7, 0xa7, 0xc4, 0xa3, 0xc5,
	0x2b, 0xa5, 0xee, 0x95, 0xd2, 0x8f, 0xdb, 0x27, 0x1c, 0x9c, 0x6d, 0x7a, 0xca, 0xe4, 0x53, 0x80,
	0x3d, 0x4c, 0x06, 0xd5, 0xd4, 0x0b, 0xc5, 0xbe, 0xbb, 0xf9, 0x0a, 0x52, 0xc4, 0x16, 0x9e, 0x5d,
	0x19, 0x8d, 0xaf, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x69, 0x96, 0xe2, 0xb1, 0x9d, 0x04, 0x00,
	0x00,
}
