// Code generated by entc, DO NOT EDIT.

package accounts

const (
	// Label holds the string label denoting the accounts type in the database.
	Label = "accounts"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBalance holds the string denoting the balance vertex property in the database.
	FieldBalance = "balance"
	// FieldVersion holds the string denoting the version vertex property in the database.
	FieldVersion = "version"
	// FieldIsVerified holds the string denoting the is_verified vertex property in the database.
	FieldIsVerified = "is_verified"
	// FieldUserID holds the string denoting the user_id vertex property in the database.
	FieldUserID = "user_id"

	// Table holds the table name of the accounts in the database.
	Table = "accounts"
	// TxsTable is the table the holds the txs relation/edge.
	TxsTable = "txs"
	// TxsInverseTable is the table name for the Txs entity.
	// It exists in this package in order to avoid circular dependency with the "txs" package.
	TxsInverseTable = "txs"
	// TxsColumn is the table column denoting the txs relation/edge.
	TxsColumn = "accounts_id"
)

// Columns holds all SQL columns for accounts fields.
var Columns = []string{
	FieldID,
	FieldBalance,
	FieldVersion,
	FieldIsVerified,
	FieldUserID,
}
