// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateDepositParams struct {
	UserId               int64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount               int64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	ReferenceNumber      *wrappers.StringValue `protobuf:"bytes,3,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateDepositParams) Reset()         { *m = CreateDepositParams{} }
func (m *CreateDepositParams) String() string { return proto.CompactTextString(m) }
func (*CreateDepositParams) ProtoMessage()    {}
func (*CreateDepositParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *CreateDepositParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDepositParams.Unmarshal(m, b)
}
func (m *CreateDepositParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDepositParams.Marshal(b, m, deterministic)
}
func (m *CreateDepositParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDepositParams.Merge(m, src)
}
func (m *CreateDepositParams) XXX_Size() int {
	return xxx_messageInfo_CreateDepositParams.Size(m)
}
func (m *CreateDepositParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDepositParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDepositParams proto.InternalMessageInfo

func (m *CreateDepositParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateDepositParams) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CreateDepositParams) GetReferenceNumber() *wrappers.StringValue {
	if m != nil {
		return m.ReferenceNumber
	}
	return nil
}

type CreateWithdrawParams struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWithdrawParams) Reset()         { *m = CreateWithdrawParams{} }
func (m *CreateWithdrawParams) String() string { return proto.CompactTextString(m) }
func (*CreateWithdrawParams) ProtoMessage()    {}
func (*CreateWithdrawParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *CreateWithdrawParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWithdrawParams.Unmarshal(m, b)
}
func (m *CreateWithdrawParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWithdrawParams.Marshal(b, m, deterministic)
}
func (m *CreateWithdrawParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWithdrawParams.Merge(m, src)
}
func (m *CreateWithdrawParams) XXX_Size() int {
	return xxx_messageInfo_CreateWithdrawParams.Size(m)
}
func (m *CreateWithdrawParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWithdrawParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWithdrawParams proto.InternalMessageInfo

func (m *CreateWithdrawParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateWithdrawParams) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type CreateAccountParams struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountParams) Reset()         { *m = CreateAccountParams{} }
func (m *CreateAccountParams) String() string { return proto.CompactTextString(m) }
func (*CreateAccountParams) ProtoMessage()    {}
func (*CreateAccountParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *CreateAccountParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountParams.Unmarshal(m, b)
}
func (m *CreateAccountParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountParams.Marshal(b, m, deterministic)
}
func (m *CreateAccountParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountParams.Merge(m, src)
}
func (m *CreateAccountParams) XXX_Size() int {
	return xxx_messageInfo_CreateAccountParams.Size(m)
}
func (m *CreateAccountParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountParams proto.InternalMessageInfo

func (m *CreateAccountParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetAccountParams struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountParams) Reset()         { *m = GetAccountParams{} }
func (m *GetAccountParams) String() string { return proto.CompactTextString(m) }
func (*GetAccountParams) ProtoMessage()    {}
func (*GetAccountParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *GetAccountParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountParams.Unmarshal(m, b)
}
func (m *GetAccountParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountParams.Marshal(b, m, deterministic)
}
func (m *GetAccountParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountParams.Merge(m, src)
}
func (m *GetAccountParams) XXX_Size() int {
	return xxx_messageInfo_GetAccountParams.Size(m)
}
func (m *GetAccountParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountParams proto.InternalMessageInfo

func (m *GetAccountParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Account struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Balance              int64    `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Account) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UpdateAccountVerifiedParams struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountVerifiedParams) Reset()         { *m = UpdateAccountVerifiedParams{} }
func (m *UpdateAccountVerifiedParams) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountVerifiedParams) ProtoMessage()    {}
func (*UpdateAccountVerifiedParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *UpdateAccountVerifiedParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountVerifiedParams.Unmarshal(m, b)
}
func (m *UpdateAccountVerifiedParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountVerifiedParams.Marshal(b, m, deterministic)
}
func (m *UpdateAccountVerifiedParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountVerifiedParams.Merge(m, src)
}
func (m *UpdateAccountVerifiedParams) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountVerifiedParams.Size(m)
}
func (m *UpdateAccountVerifiedParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountVerifiedParams.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountVerifiedParams proto.InternalMessageInfo

func (m *UpdateAccountVerifiedParams) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateDepositParams)(nil), "pepeunlimited.accounts.CreateDepositParams")
	proto.RegisterType((*CreateWithdrawParams)(nil), "pepeunlimited.accounts.CreateWithdrawParams")
	proto.RegisterType((*CreateAccountParams)(nil), "pepeunlimited.accounts.CreateAccountParams")
	proto.RegisterType((*GetAccountParams)(nil), "pepeunlimited.accounts.GetAccountParams")
	proto.RegisterType((*Account)(nil), "pepeunlimited.accounts.Account")
	proto.RegisterType((*UpdateAccountVerifiedParams)(nil), "pepeunlimited.accounts.UpdateAccountVerifiedParams")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x5d, 0x6b, 0xc2, 0x40,
	0x10, 0x24, 0x06, 0x14, 0x56, 0xb4, 0x72, 0x6d, 0x6d, 0xd0, 0xd2, 0x4a, 0x9e, 0x04, 0xcb, 0x09,
	0x0a, 0x7d, 0xef, 0x07, 0x48, 0xa1, 0x94, 0xa2, 0x54, 0xa1, 0x50, 0xe4, 0x92, 0xac, 0xf6, 0x20,
	0x1f, 0xc7, 0xe5, 0x52, 0xe9, 0xaf, 0xe8, 0xcf, 0xed, 0x6b, 0xd1, 0x24, 0xda, 0x88, 0x9a, 0xd2,
	0xc7, 0xdd, 0x9d, 0x99, 0x9d, 0xcb, 0x6c, 0xa0, 0xc2, 0x6c, 0x3b, 0x88, 0x7c, 0x45, 0x85, 0x0c,
	0x54, 0x40, 0xea, 0x02, 0x05, 0x46, 0xbe, 0xcb, 0x3d, 0xae, 0xd0, 0xa1, 0xc9, 0x30, 0x6c, 0x34,
	0xe7, 0x41, 0x30, 0x77, 0xb1, 0xbb, 0x42, 0x59, 0xd1, 0xac, 0x8b, 0x9e, 0x50, 0x9f, 0x31, 0xa9,
	0x71, 0xb1, 0x3d, 0x5c, 0x48, 0x26, 0x04, 0xca, 0x30, 0x9e, 0x9b, 0x5f, 0x1a, 0x1c, 0xdf, 0x49,
	0x64, 0x0a, 0xef, 0x51, 0x04, 0x21, 0x57, 0xcf, 0x4c, 0x32, 0x2f, 0x24, 0x67, 0x50, 0x8a, 0x42,
	0x94, 0x53, 0xee, 0x18, 0x5a, 0x4b, 0x6b, 0xeb, 0xc3, 0xe2, 0xb2, 0x7c, 0x70, 0x48, 0x1d, 0x8a,
	0xcc, 0x5b, 0x2e, 0x36, 0x0a, 0x71, 0x3f, 0xae, 0xc8, 0x00, 0x6a, 0x12, 0x67, 0x28, 0xd1, 0xb7,
	0x71, 0xea, 0x47, 0x9e, 0x85, 0xd2, 0xd0, 0x5b, 0x5a, 0xbb, 0xdc, 0x3b, 0xa7, 0xb1, 0x07, 0x9a,
	0x7a, 0xa0, 0x23, 0x25, 0xb9, 0x3f, 0x1f, 0x33, 0x37, 0xc2, 0xe1, 0xd1, 0x9a, 0xf5, 0xb4, 0x22,
	0x99, 0x03, 0x38, 0x89, 0x0d, 0x4d, 0xb8, 0x7a, 0x77, 0x24, 0x5b, 0xfc, 0xd3, 0x91, 0x49, 0xd3,
	0x97, 0xdd, 0xc4, 0x5f, 0x2a, 0x47, 0xc7, 0xec, 0x40, 0x6d, 0x80, 0xea, 0x8f, 0xe0, 0x47, 0x28,
	0x25, 0x48, 0x52, 0x85, 0xc2, 0x7a, 0x5c, 0xe0, 0x0e, 0x31, 0xa0, 0x64, 0x31, 0x97, 0xf9, 0x36,
	0x26, 0x86, 0xd2, 0xf2, 0xb7, 0x9a, 0x9e, 0x51, 0xbb, 0x86, 0xe6, 0x8b, 0x70, 0x36, 0x56, 0xc7,
	0x28, 0xf9, 0x8c, 0xa3, 0x93, 0xe3, 0xa2, 0xf7, 0xad, 0x43, 0x35, 0xa1, 0x8c, 0x50, 0x7e, 0x70,
	0x1b, 0xc9, 0x1b, 0x54, 0x32, 0x79, 0x92, 0x0e, 0xdd, 0x7d, 0x37, 0x74, 0x47, 0xec, 0x8d, 0xcb,
	0x7d, 0xe0, 0xf4, 0xb1, 0x53, 0xa8, 0x66, 0xd3, 0x21, 0x57, 0x87, 0xf5, 0xb3, 0x29, 0xe6, 0x2f,
	0x58, 0xfb, 0x4f, 0x1b, 0x39, 0xfe, 0x33, 0x79, 0xe5, 0xcb, 0x4f, 0x00, 0x36, 0x21, 0x93, 0xf6,
	0x3e, 0xf8, 0xf6, 0x21, 0xe4, 0x0b, 0x7b, 0x70, 0xba, 0x33, 0x42, 0xd2, 0xdf, 0xc7, 0x3c, 0x90,
	0x78, 0xee, 0xba, 0xdb, 0xca, 0x6b, 0x39, 0xed, 0x49, 0x61, 0x5b, 0xc5, 0xd5, 0xbf, 0xd5, 0xff,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xab, 0xe6, 0xab, 0x89, 0x33, 0x04, 0x00, 0x00,
}
