// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pepeunlimited/accounts/internal/app/app1/ent/accounts"
	"github.com/pepeunlimited/accounts/internal/app/app1/ent/predicate"
)

// AccountsDelete is the builder for deleting a Accounts entity.
type AccountsDelete struct {
	config
	predicates []predicate.Accounts
}

// Where adds a new predicate to the delete builder.
func (ad *AccountsDelete) Where(ps ...predicate.Accounts) *AccountsDelete {
	ad.predicates = append(ad.predicates, ps...)
	return ad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ad *AccountsDelete) Exec(ctx context.Context) (int, error) {
	return ad.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (ad *AccountsDelete) ExecX(ctx context.Context) int {
	n, err := ad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ad *AccountsDelete) sqlExec(ctx context.Context) (int, error) {
	spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: accounts.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: accounts.FieldID,
			},
		},
	}
	if ps := ad.predicates; len(ps) > 0 {
		spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ad.driver, spec)
}

// AccountsDeleteOne is the builder for deleting a single Accounts entity.
type AccountsDeleteOne struct {
	ad *AccountsDelete
}

// Exec executes the deletion query.
func (ado *AccountsDeleteOne) Exec(ctx context.Context) error {
	n, err := ado.ad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &ErrNotFound{accounts.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ado *AccountsDeleteOne) ExecX(ctx context.Context) {
	ado.ad.ExecX(ctx)
}
