// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Accounts is the predicate function for accounts builders.
type Accounts func(*sql.Selector)

// Txs is the predicate function for txs builders.
type Txs func(*sql.Selector)
